{% set name = "ncas-amof-netcdf-template" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ncas_amof_netcdf_template-{{ version }}.tar.gz
  sha256: d90d16315ef915e7348097f8b2a900e6901036bfee358cc714290e45903f2366

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
  run:
    - python >=3.7,<4.0
    - netcdf4
    - numpy
    - requests
    - pandas

test:
  imports:
    - ncas_amof_netcdf_template
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/joshua-hampton/ncas_amof_netcdf_template
  summary: Package to create NCAS AMOF netCDF files.
  license: MIT
  license_file: LICENSE
  doc_url: https://ncas-amof-netcdf-template.readthedocs.io/en/stable/index.html

extra:
  recipe-maintainers:
    - joshua-hampton
